dubbo:
  application:
    name: class-service
  registry:
    address: zookeeper://119.23.79.138:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_class?serverTimezone=GMT%2B8
    username: root
    password: root