dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://192.168.211.128:2181
  protocol:
    port: -1
    #首次启动不检查提供者
  consumer:
    check: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_student?serverTimezone=GMT%2B8
    username: root
    password: root