dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://119.23.79.138:2181
  protocol:
    port: -1
    #首次启动不检查提供者
  consumer:
    check: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: root